In [2]:
import torch
print(torch.__version__)

2.9.0+cu126


CREATING AND INITIALIZATION of TENSORS

In [ ]:
#using empty
#space assign karta hai aur us memory space me jo already value hai vo return karta hai
torch.empty(2,3)

tensor([[0.0000e+00, 1.6255e-43, 7.7052e+31],
        [1.9447e+31, 2.1715e-18, 2.3081e-12]])

In [ ]:
a=torch.empty(2,3)
type(a)

torch.Tensor

In [ ]:
#using zeros
#for weight initialization purposes
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
#using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
#using rand
torch.rand(2,3)

tensor([[0.1095, 0.5542, 0.3247],
        [0.8790, 0.9980, 0.3602]])

In [ ]:
torch.rand(2,3)
#different random values
#reproducibility must be same each time for experimentation
#use manual_seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [ ]:
torch.manual_seed(100)
torch.rand(2,3)
#u can see u are getting same value of tensors each time

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [ ]:
#using tensor
#customize tensors (apke manpasand ke tensors)
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
#other wauys
#arange
print(torch.arange(0,10,2))
#linspace
#linearly spaced or evenly spaced values
torch.linspace(0,20,10)
##othe ways are full and eye

tensor([0, 2, 4, 6, 8])


tensor([ 0.0000,  2.2222,  4.4444,  6.6667,  8.8889, 11.1111, 13.3333, 15.5556,
        17.7778, 20.0000])

TENSOR SHAPES


In [ ]:
x=torch.tensor([[1,2,3],[4,5,6]])
print(x.shape)

torch.Size([2, 3])


In [ ]:
#create a tensor with the same shape as x tensor
#using empty_like
torch.empty_like(x)
#ones_like, zeros_like and rand_like
#but for this rand_like wont work

tensor([[7309453675965983778, 8315168162784306286, 8367752027310484831],
        [7954801838398993778, 2459029315949324647, 3905807474979005752]])

In [ ]:
torch.rand_like(x, dtype=torch.float32)#rand generate between 0 to 1 float but we have int in x tensors

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

TENSORS DATA TYPES

In [ ]:
x.dtype

torch.int64

In [ ]:
#assignning data type during initialization of tensors
torch.tensor([1.0,2.3,3.5], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [ ]:
#dirrect conversion using " to "
x.to(torch.int32)

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)

**BASIC INDEXING**

In [35]:
x = torch.tensor([10, 20, 30, 40, 50])

print(x[0])     # First element
print(x[-1])    # Last element

tensor(10)
tensor(50)


Slicing (1D Tensor)

In [36]:
print(x[1:4])     # From index 1 to 3
print(x[:3])      # First 3 elements
print(x[::2])     # with Step size = 2


tensor([20, 30, 40])
tensor([10, 20, 30])
tensor([10, 30, 50])


Indexing in 2D Tensors

In [37]:
mat = torch.tensor([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [39]:
mat[1,2]

tensor(6)

Slicing in 2D Tensors

In [41]:
# First two rows, last two columns
sub = mat[:2, 1:]
sub

tensor([[2, 3],
        [5, 6]])

Boolean Masking

In [42]:
x = torch.tensor([5, 10, 15, 20, 25])

mask = x > 15


In [43]:
mask

tensor([False, False, False,  True,  True])

In [44]:
x[mask]

tensor([20, 25])

In [45]:
x[x % 10 == 0]

tensor([10, 20])

In [47]:
#in 2d tensors
mat = torch.tensor([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])
mat[mat > 50]

tensor([60, 70, 80, 90])

**Extracting Subtensors**

In [48]:
# Extract center 2x2 matrix
sub_tensor = mat[1:3, 1:3]
sub_tensor

tensor([[50, 60],
        [80, 90]])

In [50]:
tensor = torch.arange(2*3*4).reshape(2, 3, 4)
tensor

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [51]:
#extracting from 3d tensor
# First block, rows 1–2, columns 0–1
sub = tensor[0, 1:3, 0:2]
sub

tensor([[4, 5],
        [8, 9]])

**MATHEMATICAL OPERATION**

**1. SCALAR OPERATIONS**

In [ ]:
x=torch.rand(2,3)
x

tensor([[0.4440, 0.9478, 0.7445],
        [0.4892, 0.2426, 0.7003]])

In [ ]:
#addition
x+2
#multiplicatiom
x*2
#division
x*100//3
x*100/3
#mod
x%2
#power
x**2

tensor([[0.1972, 0.8984, 0.5543],
        [0.2393, 0.0588, 0.4905]])


**2. ELEMENT WISE OPERATIONS**

In [ ]:
#BETWEEN ELEMENTS OF TWO MATRIX
#a+b
#a-b
#a%b

**other -> abs, negative, round, floor, ceil**

In [ ]:
#clampp
x= torch.tensor([1,2,0,4,5,6,7])
#torch.ceil(x)
torch.clamp(x, min=2, max=3)# 2 se niche vale 2 ban jayenge and 3 se bade vale 3 ban jayenge


tensor([2, 2, 2, 3, 3, 3, 3])

**3. REDUCTION LIKE NUMPY -> SUM, MEAN, AVERAGE -> CONVERSION TO A SINGLE VALUE**

In [ ]:
e = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
e

tensor([[9., 9., 3.],
        [6., 1., 2.]])

In [ ]:
#sum
torch.sum(e)
#sum along columns -> left to right
torch.sum(e, dim=1)
#sum along rows ->up to down
torch.sum(e, dim=0)

tensor([17., 10.,  8.])

In [ ]:
#mean of whole tensor
torch.mean(e)
#mean along column
torch.mean(e, dim=1)
#mean along row
torch.mean(e, dim=0)

tensor([8.5000, 5.0000, 4.0000])

In [ ]:
#median
torch.median(e)

tensor(6.)

In [ ]:
# max min
torch.max(e)
torch.min(e)

tensor(2.)

In [ ]:
#standard deviation


In [ ]:
#variance

In [ ]:
#product
torch.prod(e)

tensor(18144.)

In [ ]:
#argmax
#position or index of min and max element (0 to n-1) range
torch.argmax(e)
torch.argmin(e)

tensor(4)

4. **MATRIX OPERATIONS**




In [27]:
f = torch.randint(size=(2,3), low=0, high=10)
g = torch.randint(size=(3,2), low=0, high=10)

print(f)
print(g)

tensor([[2, 9, 6],
        [8, 7, 8]])
tensor([[2, 5],
        [7, 1],
        [8, 8]])


In [28]:
#MATRIX MULTIPLICATION
torch.matmul(f, g)

tensor([[115,  67],
        [129, 111]])

In [29]:
vector1 = torch.tensor([1, 2])
vector2 = torch.tensor([3, 4])
#DOT PRODUCT

torch.dot(vector1, vector2)

tensor(11)

In [30]:
#TRANSPOSE

torch.transpose(f, 0, 1)

tensor([[2, 8],
        [9, 7],
        [6, 8]])

In [32]:
h = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
h

tensor([[2., 7., 8.],
        [2., 9., 4.],
        [3., 1., 6.]])

In [33]:
#DETERMINANT
torch.det(h)

tensor(-100.)

In [34]:
#INVERSE
torch.inverse(h)

tensor([[-0.5000,  0.3400,  0.4400],
        [ 0.0000,  0.1200, -0.0800],
        [ 0.2500, -0.1900, -0.0400]])

5. **COMPARISON OPERATIONS**

In [ ]:
#GREATER THAN

#LESS THAN

#EQUAL TO

#GREATER THAN AND EQUAL TO

6. **SPECIAL OPERATIONS**

In [ ]:
#LOG

#EXP

#SQRT

#SIGMOID

#SOFTMAX

#RELU

**INPLACE OPERATIONS**

In [18]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.5560, 0.4311, 0.0580],
        [0.1507, 0.5155, 0.4023]])
tensor([[0.4102, 0.8617, 0.8452],
        [0.5287, 0.1865, 0.0100]])


In [20]:
m.add_(n)

tensor([[1.3764, 2.1545, 1.7484],
        [1.2081, 0.8885, 0.4223]])

In [21]:
m

tensor([[1.3764, 2.1545, 1.7484],
        [1.2081, 0.8885, 0.4223]])

In [22]:
n

tensor([[0.4102, 0.8617, 0.8452],
        [0.5287, 0.1865, 0.0100]])

In [23]:
torch.relu(m)

tensor([[1.3764, 2.1545, 1.7484],
        [1.2081, 0.8885, 0.4223]])

In [25]:
m.relu_()

tensor([[1.3764, 2.1545, 1.7484],
        [1.2081, 0.8885, 0.4223]])

In [26]:
m

tensor([[1.3764, 2.1545, 1.7484],
        [1.2081, 0.8885, 0.4223]])

7. **COPYING A TENSOR**

In [ ]:
#PROBLEM WHILE COPYING
a = torch.randint(size=(2,3), low=1, high=10)
a

tensor([[6, 1, 6],
        [1, 4, 9]])

In [ ]:
b=a

In [ ]:
b

tensor([[6, 1, 6],
        [1, 4, 9]])

In [ ]:
a[0][0]=0
a

tensor([[0, 1, 6],
        [1, 4, 9]])

In [ ]:
b #so you saw that even by making a copy still both a and b are modifying simultaneoulsy, so its a waste to make copy
#what is actually happening here is you are referencing b to the same position as a pointing
#that, means id(a) is equal to id(b)

tensor([[0, 1, 6],
        [1, 4, 9]])

In [ ]:
id(a)

136331038046992

In [ ]:
id(b)

136331038046992

In [ ]:
#axctual copy formed
#this is actually a new copy
b=a.clone()

*** TENSORS OPERATIONS OVER GPU ***

In [ ]:
torch.cuda.is_available()

True

In [ ]:
#torch.device('cuda') is a standard way in the PyTorch deep learning framework to specify that a tensor or model should be
#allocated and run on the GPU (Graphics Processing Unit), assuming one is available and properly configured

#This indicates that PyTorch is utilizing NVIDIA's CUDA platform to leverage the parallel
# processing power of the GPU for faster computations.
device = torch.device('cuda')

In [ ]:
#creating a new tensor on GPU
a=torch.rand(size=(2,3), device=device)
a

tensor([[0.4870, 0.1912, 0.9787],
        [0.6837, 0.4247, 0.2974]], device='cuda:0')

In [ ]:
#moving an existing tensor to GPU
b=torch.rand(2,3) #this is formed inside CPU

In [ ]:
b.to(device)

tensor([[0.5309, 0.9216, 0.1519],
        [0.9281, 0.8097, 0.0042]], device='cuda:0')

**RESHAPING TENSORS**

In [5]:
a = torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [7]:
#reshape
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [8]:
#flatten
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [9]:
#unsqueeze -> adding extra dimension
#image size
c=torch.rand(226,226,3)
c.unsqueeze(0).shape #adding dimension at very first dimension

torch.Size([1, 226, 226, 3])

In [10]:
#reversing of unsqeezing
c=torch.rand(1,20)
c.squeeze(0).shape

torch.Size([20])

**NUMPY AND PYTORCH**

In [11]:
#You can easily convert numpy arrays into pytorch tensors or vice versa

In [13]:
a=torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [14]:
import numpy as np

In [16]:
#conversion from tensor to numpy
b=a.numpy()
type(b)

numpy.ndarray

In [17]:
#conversion from numpy to tensors
torch.from_numpy(b)

tensor([1, 2, 3])